apiVersion: v1
kind: ConfigMap
metadata:
  name: campaign-service-configmap
  namespace: apps-campaign-service
data:
  HOST: '0.0.0.0'
  PORT: '3000'
  APP_URL: 'http://${HOST}:${PORT}'
  NODE_ENV: 'production'
  APP_NAME:  'application'
  APP_KEY: '# ------ #'
  API_VERSION: '/v1'
  CUSTOMER_SERVICE_URL: 'http://users-service-service.apps-users-service.svc.cluster.local:3000'
  POSTGRES_HOST: 'products-service.clwfjxlpe5hc.us-east-1.rds.amazonaws.com'


