apiVersion: apps/v1
kind: Deployment
metadata:
  name: campaign-service-deployment
  namespace: apps-campaign-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: campaign-service
  template:
    metadata:
      labels:
        app: campaign-service
    spec:
      containers:
        - name: campaign-service
          image: "405445518215.dkr.ecr.us-east-1.amazonaws.com/campaign-service:62bf811"
