apiVersion: v1
kind: ConfigMap
metadata:
  name: payment-service-configmap
  namespace: apps-payment-service
data:
  HOST: '0.0.0.0'
  PORT: '3000'
  APP_URL: 'http://${HOST}:${PORT}'
  SWAGGER_BASE_URL: 'https://payment.techchallenge.com.br'
  NODE_ENV: 'development'
  APP_NAME: 'application'
  API_VERSION: '/v1'
  MONGODB_HOST: 'mongodb.tool-database.svc.cluster.local'
  MONGODB_PORT: '27017'
  WEBHOOK: 'http://payment-service.svc.cluster.local:3000'
  ORDER_SERVICE_URL: 'http://orders-service-service.apps-orders-service.svc.cluster.local:3000'
  CUSTOMER_SERVICE_URL: 'http://users-service-service.apps-users-service.svc.cluster.local:3000'

