apiVersion: apps/v1
kind: Deployment
metadata:
  name: video-service-deployment
  namespace: core
spec:
  selector:
    matchLabels:
      app: hackathon
  template:
    metadata:
      labels:
        app: hackathon
    spec:
      containers:
        - name: video-service
          image: "630607855992.dkr.ecr.us-east-1.amazonaws.com/video-service:86136dc"
