apiVersion: v1
kind: Service
metadata:
  name: users-service-service
  namespace: apps-users-service
spec:
  selector:
    app: users-service
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: ClusterIP
