apiVersion: v1
kind: Service
metadata:
  name: orders-service-service
  namespace: apps-orders-service
spec:
  selector:
    app: orders-service
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: ClusterIP
