apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - role.yaml
  - configmap.yaml
  - serviceaccount.yaml
  - roleBinding.yaml

labels:
  - pairs:
      app: payment-service
    includeSelectors: true
    includeTemplates: true
