apiVersion: v1
kind: Service
metadata:
  name: products-service-service
  namespace: apps-products-service
spec:
  selector:
    app: products-service
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: ClusterIP
