apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - path: patches/serviceaccount.yaml
  - path: patches/deployment.yaml
  - path: patches/configmap.yaml