apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-service-deployment
  namespace: apps-users-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: users-service
  template:
    metadata:
      labels:
        app: users-service
    spec:
      containers:
        - name: users-service
          image: "405445518215.dkr.ecr.us-east-1.amazonaws.com/users-service:93f505e"
