apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: campaign-service-role-binding
  namespace: apps-campaign-service
subjects:
  - kind: ServiceAccount
    name: campaign-service-service-account
    namespace: apps-campaign-service
roleRef:
  kind: Role
  name: campaign-service-role
  apiGroup: rbac.authorization.k8s.io
