apiVersion: v1
kind: Service
metadata:
  name: campaign-service-service
  namespace: apps-campaign-service
spec:
  selector:
    app: campaign-service
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: ClusterIP
