apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders-service-deployment
  namespace: apps-orders-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orders-service
  template:
    metadata:
      labels:
        app: orders-service
    spec:
      containers:
        - name: orders-service
          image: "405445518215.dkr.ecr.us-east-1.amazonaws.com/orders-service:e28557a"
