apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: video-service-hpa
  namespace: core
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: video-service-deployment
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 45
