apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: video-service-role-binding
  namespace: core
subjects:
  - kind: ServiceAccount
    name: video-service-account
    namespace: core
roleRef:
  kind: Role
  name: video-service-role
  apiGroup: rbac.authorization.k8s.io
