apiVersion: v1
kind: Service
metadata:
  name: video-service-service
  namespace: core
spec:
  selector:
    app: hackathon
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: ClusterIP
