apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "helm.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "helm.labels" . | nindent 4 }}
data:
  POSTGRES_DB: {{ .Values.config.POSTGRES_DB | quote }}
  PORT: {{ .Values.config.PORT | quote }}
  API_VERSION: {{ .Values.config.API_VERSION | quote }}
  POSTGRES_HOST: {{ .Values.config.POSTGRES_HOST | quote }}
  NODE_ENV: {{ .Values.config.NODE_ENV | quote }}
  APP_NAME: {{ .Values.config.APP_NAME | quote }}
  APP_KEY: {{ .Values.config.APP_KEY | quote }}
  APP_URL: {{ .Values.config.APP_URL | quote }}
