{{- if .Values.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "helm.fullname" . }}
  namespace: {{ .Values.namespace | default "default" }}
spec:
  refreshInterval: {{ default "1h" .Values.externalSecrets.refreshInterval }}
  secretStoreRef:
    name: {{ default "secrets-store-external" .Values.externalSecrets.secretsStoreRef }}
    kind: ClusterSecretStore
  target:
    name: {{ default "tech-challenge-secret" .Values.externalSecrets.target.name }}
    creationPolicy: {{ default "Owner" .Values.externalSecrets.target.creationPolicy }}
  data:
  {{- range .Values.externalSecrets.data }}
    - secretKey: {{ .secretKey }}
      remoteRef:
        key: {{ .remoteRef.key }}
        property: {{ .remoteRef.property }}
  {{- end }}
{{- end }}